MainPage/urls.py
from sys import path

from django.conf.urls import url
from . import views

app_name = 'FirstTry'
urlpatterns = [
    url('create_students/', views.create_students, name="create_students"),
    url(r'students_in_groups/(?P<pk>\d+)/', views.students_in_groups, name="students_in_groups"),
    url(r'students/(?P<pk>\d+)/', views.Newsupdate_Students.as_view(), name="studente"),
    url(r'students_delete/(?P<pk>\d+)/', views.Delete_students.as_view(), name="studente_delete"),
    url(r'groups_delete/(?P<pk>\d+)/', views.Delete_groups.as_view(), name="groups_delete"),
    url(r'groups/(?P<pk>\d+)/', views.Newsupdate_groups.as_view(), name="groups_up"),
    url(r'students', views.search_students, name="students"),
    url('create_groups/', views.create_groups, name="create"),
    url(r'groups/', views.search_groups, name="groups"),
    url(r'', views.search_groups, name="groups"),
]

mydjango/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('MainPage.urls', namespace='page1')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MainPage/models.py
import form as form
from django.db import models

def _get_groups() -> tuple:
    name = Arcticles.objects.all()
    a = []
    for i in range((len(name))):
        b = []
        b.append(str(name[i]))
        b.append(str(name[i]))
        a.append(b)
    return tuple(a)


class Arcticles(models.Model):
    number_group = models.CharField('Номер группы ', max_length=50)
    special = models.CharField('Специальность ', max_length=100)

    def __str__(self):
        return self.number_group

    def get_absolute_url(self):
        return f'/groups/'

    class Meta:
        verbose_name_plural = 'Группы'


class Arcticles_Students(models.Model):
    fullname = models.CharField('Фамилия ', max_length=50)
    name = models.CharField('Имя ', max_length=100)
    otchest = models.CharField('Отчество ', max_length=100)
    category1 = models.ForeignKey(Arcticles, verbose_name="Группа", on_delete=models.SET_NULL, null=True)


    def __str__(self):
        return self.fullname + " " + self.name + " " + self.otchest

    def get_absolute_url(self):
        return f'/students/'


    class Meta:
        verbose_name_plural = 'Студенты'

MainPage/forms.py
from django.utils.regex_helper import Choice

from .models import Arcticles, Arcticles_Students, _get_groups
from django.forms import ModelForm, TextInput, SelectDateWidget, DateField, fields, Select, ChoiceField


class ArcticlesForm(ModelForm):
    class Meta:
        model = Arcticles
        fields = ['number_group', 'special', ]

        widgets = {
            "number_group": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Номер группы'
            }),
            "special": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Специальность',

            }),

        }


class Arcticles_Form_Students(ModelForm):
    class Meta:
        model = Arcticles_Students
        fields = ['fullname', 'name', 'otchest', 'category1']
        widgets = {
            "fullname": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Фамилия'
            }),
            "name": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Имя'
            }),
            "otchest": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Отчество'
            }),
            "category1": Select(attrs={
                'class': 'form-control',
            }),
        }

MainPage/views.py
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.contrib.auth.models import User
from .models import Arcticles, Arcticles_Students, _get_groups
from .forms import ArcticlesForm, Arcticles_Form_Students
from django.views.generic import UpdateView, DetailView, DeleteView
from django.shortcuts import render, redirect


class Newsupdate_Students(UpdateView):
    model = Arcticles_Students
    template_name = 'myPage1/create_students.html'
    form_class = Arcticles_Form_Students


class Newsupdate_groups(UpdateView):
    model = Arcticles
    template_name = 'myPage1/create_groups.html'
    form_class = ArcticlesForm


class Delete_students(DeleteView):
    model = Arcticles_Students
    template_name = 'myPage1/delete_students.html'
    success_url = '/students/'


class Delete_groups(DeleteView):
    model = Arcticles
    template_name = 'myPage1/delete_groups.html'
    success_url = '/groups/'


def search_groups(request):
    name = Arcticles.objects.all()
    _get_groups()
    return render(request, 'myPage1/groups.html', {'name': name,
                                                   'count_students': count_students_in_groups(request)})


def students_in_groups(request, pk):
    id_group = Arcticles.objects.filter(id=pk);
    students = Arcticles_Students.objects.all()
    c=[]
    for i in students:
        if (id_group[0] == i.category1):
            c.append(i)
    return render(request, 'myPage1/find_students_in_groups.html',
                  {'answer': c} )


def count_students_in_groups(request):
    groups = _get_groups()
    c = []
    c2=[]
    student = Arcticles_Students.objects.all()
    for i in student:
        c.append(i.category1)
    v=list(c)
    for y in groups:
        try:
            n = 0
            c1 = []
            for i in v:
                if (i.number_group == y[0]):
                    n = n + 1
            c1.append(y[0])
            c1.append(n)
            c2.append(c1)
        except:
            c1.append(y[0])
            c1.append("0")
            c2.append(c1)
    return tuple(c2)


def search_students(request):
    name = Arcticles_Students.objects.all()
    return render(request, 'myPage1/students.html', {'name': name})


def create_groups(request):
    error = ''
    if request.method == 'POST':
        form = ArcticlesForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('FirstTry:groups')
        else:
            error = " Форма неверна заполнена"
    form = ArcticlesForm()
    data = {
        'form': form,
        'error': error
    }

    return render(request, 'myPage1/create_groups.html', data)


def create_students(request):
    error = ''
    if request.method == 'POST':
        form = Arcticles_Form_Students(request.POST)
        if form.is_valid():
            form.save()
            return redirect('FirstTry:students')
        else:
            error = " Форма неверна заполнена"
    form = Arcticles_Form_Students()
    data = {
        'form': form,
        'error': error
    }
    return render(request, 'myPage1/create_students.html', data)

MainPage/templates/myPage1/create_groups.html
{%extends 'myPage1/mainTheme.html'%}
{%block content%}
    <div class="features">
        <h1> Форма по добавлению</h1>
        <form method="post">
             {% csrf_token %}
           {{form.number_group}} <br>
            {{form.special}} <br>
            <span>{{error}}</span>
            <button class="btn btn-success" type="submit"> Добавить</button>
            <a class="btn btn-danger" href="{% url 'FirstTry:groups'%}" role="button">Отмена</a>
        </form>
    </div>
{%endblock%}

MainPage/templates/myPage1/create_students.html
{%extends 'myPage1/mainTheme.html'%}
{%block content%}
    <div class="features">
        <h1> Форма по добавлению</h1>
        <form method="post">
             {% csrf_token %}
            {{form.repair_cost_estimate}}<br>
            {{form.fullname}} <br>
            {{form.name}} <br>
            {{form.otchest }} <br>
            {{form.category1}} <br>
            <span>{{error}}</span>
            <button class="btn btn-success" type="submit"> Добавить</button>
            <a class="btn btn-danger" href="{% url 'FirstTry:students'%}" role="button">Отмена</a>
        </form>

    </div>
{%endblock%}

MainPage/templates/myPage1/delete_groups.html
{%extends 'myPage1/mainTheme.html'%}
{%block link%} href="{% url 'FirstTry:create_students'%}" {%endblock%}
{%block content%}

            <div class="alert alert-warning">
                   <form method="post">
                     {% csrf_token %}
                       <h1>Вы уверены?</h1>>
                     <button class="btn btn-danger" onclick="return confirm('Эти действия приведут к полному удалению. Ты уверен , что хочешь продолжить?')" type="submit">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'FirstTry:groups'%}" role="button">Отмена</a>
                   </form>

            </div>

{%endblock%}

MainPage/templates/myPage1/delete_students.html
{%extends 'myPage1/mainTheme.html'%}
{%block link%} href="{% url 'FirstTry:create_students'%}" {%endblock%}
{%block content%}

            <div class="alert alert-warning">
                   <form method="post">
                     {% csrf_token %}
                       <h1>Вы уверены?</h1>>
                     <button class="btn btn-danger" onclick="return confirm('Эти действия приведут к полному удалению. Ты уверен , что хочешь продолжить?')" type="submit">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'FirstTry:students'%}" role="button">Отмена</a>
                   </form>

            </div>

{%endblock%}

MainPage/templates/myPage1/find_students_in_groups.html
{%extends 'myPage1/mainTheme.html'%}
{%block link%} href="{% url 'FirstTry:create'%}" {%endblock%}
{%block content%}
<div class="alert alert-warning">
      <h1>В группе {{ group}} находятся: </h1>
     <form method="POST">
                {% csrf_token %}
          {% for el1 in answer %}
         <p>{{el1}}</p>
            {% endfor %}
           </form>
     </div>

{%endblock%}

MainPage/templates/myPage1/groups.html
{%extends 'myPage1/mainTheme.html'%}
{%block link%} href="{% url 'FirstTry:create'%}" {%endblock%}
{%block content%}
       {%for el in name%}
            <form method="POST">
                {% csrf_token %}
            <div class="alert alert-warning">
                   
                <p>{{el.number_group}}</p>
                <p>{{el.special}}</p>
                {% for el1 in count_students %}
                {% if el.number_group == el1.0 %}
                <p>Численность: <a href="{% url 'FirstTry:students_in_groups' el.id%}"> {{el1.1}}</a> </p>
                {%endif%}
                {%endfor%}
                 <a href="{% url 'FirstTry:groups_up' el.id%}">Изменить</a> | <a href="{% url 'FirstTry:groups_delete' el.id%}">Удалить</a></td>
            </div>
           </form>
       {% endfor %}
{%endblock%}

MainPage/templates/myPage1/mainTheme.html
<!DOCTYPE html>
<html lang="en">
   {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'myPage1/css/main.css' %}">
    <style type="text/css">
       </style>
</head>
    <nav class="top-menu">
         {% csrf_token %}
        <ul class="menu-main">
          <li><a  href="{% url 'FirstTry:groups'%}" >Группы</a></li>
          <li><a href="{% url 'FirstTry:students'%}">Студенты</a></li>
            <a {%block link%}  {%endblock%}> <li><button class="btn btn-info"><i class="fas fa-plus-circle"></i>  Добавить </button></li></a>
        </ul>
      </nav>
       {%block content%}
        {% endblock %}

</body>
</html>

MainPage/templates/myPage1/students.html
{%extends 'myPage1/mainTheme.html'%}
{%block link%} href="{% url 'FirstTry:create_students'%}" {%endblock%}
{%block content%}
       {%for el in name%}

            <div class="alert alert-warning">
                {{el.id}}
                {{el.fullname}}
                {{el.name}}
                {{el.otchest}}
                {{el.category1}}
                <a href="{% url 'FirstTry:studente' el.id %}">Изменить</a> | <a href="{% url 'FirstTry:studente_delete' el.id%}" >Удалить</a>
            </div>

       {% endfor %}
  {% endblock %}